<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/CommConsParticipate.php");
	include("$currDir/CommConsParticipate_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('CommConsParticipate');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "CommConsParticipate";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`CommConsParticipate`.`id`" => "id",
		"`CommConsParticipate`.`ccpID`" => "ccpID",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, '; ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "WorkLocationID",
		"if(`CommConsParticipate`.`fo_WorkDate`,date_format(`CommConsParticipate`.`fo_WorkDate`,'%m/%d/%Y'),'')" => "fo_WorkDate",
		"if(`CommConsParticipate`.`fo_RequiredDate`,date_format(`CommConsParticipate`.`fo_RequiredDate`,'%m/%d/%Y'),'')" => "fo_RequiredDate",
		"CONCAT_WS('-', LEFT(`CommConsParticipate`.`ot_FileLoc`,3), MID(`CommConsParticipate`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`CommConsParticipate`.`ot_otherdetails`" => "ot_otherdetails",
		"`CommConsParticipate`.`ot_comments`" => "ot_comments",
		"`CommConsParticipate`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`CommConsParticipate`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`CommConsParticipate`.`ot_Ref01`" => "ot_Ref01",
		"`CommConsParticipate`.`ot_Ref02`" => "ot_Ref02",
		"`CommConsParticipate`.`ot_Photo`" => "ot_Photo",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`CommConsParticipate`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`CommConsParticipate`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`CommConsParticipate`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`CommConsParticipate`.`ot_ap_filed`, '%c/%e/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`CommConsParticipate`.`ot_ap_lastmodified`, '%c/%e/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`CommConsParticipate`.`id`',
		2 => 2,
		3 => 3,
		4 => '`CommConsParticipate`.`fo_WorkDate`',
		5 => '`CommConsParticipate`.`fo_RequiredDate`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => '`Leadership1`.`Status`',
		15 => 15,
		16 => '`Approval1`.`Status`',
		17 => 17,
		18 => '`IMSControl1`.`Status`',
		19 => 19,
		20 => '`CommConsParticipate`.`ot_ap_filed`',
		21 => '`CommConsParticipate`.`ot_ap_lastmodified`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`CommConsParticipate`.`id`" => "id",
		"`CommConsParticipate`.`ccpID`" => "ccpID",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, '; ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "WorkLocationID",
		"if(`CommConsParticipate`.`fo_WorkDate`,date_format(`CommConsParticipate`.`fo_WorkDate`,'%m/%d/%Y'),'')" => "fo_WorkDate",
		"if(`CommConsParticipate`.`fo_RequiredDate`,date_format(`CommConsParticipate`.`fo_RequiredDate`,'%m/%d/%Y'),'')" => "fo_RequiredDate",
		"CONCAT_WS('-', LEFT(`CommConsParticipate`.`ot_FileLoc`,3), MID(`CommConsParticipate`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`CommConsParticipate`.`ot_otherdetails`" => "ot_otherdetails",
		"`CommConsParticipate`.`ot_comments`" => "ot_comments",
		"`CommConsParticipate`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`CommConsParticipate`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`CommConsParticipate`.`ot_Ref01`" => "ot_Ref01",
		"`CommConsParticipate`.`ot_Ref02`" => "ot_Ref02",
		"`CommConsParticipate`.`ot_Photo`" => "ot_Photo",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`CommConsParticipate`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`CommConsParticipate`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`CommConsParticipate`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`CommConsParticipate`.`ot_ap_filed`, '%c/%e/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`CommConsParticipate`.`ot_ap_lastmodified`, '%c/%e/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`CommConsParticipate`.`id`" => "ID",
		"`CommConsParticipate`.`ccpID`" => "Communication Consulation & Participation ID",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, '; ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "Work Location",
		"`CommConsParticipate`.`fo_WorkDate`" => "Program Date",
		"`CommConsParticipate`.`fo_RequiredDate`" => "End Date",
		"`CommConsParticipate`.`ot_FileLoc`" => "File Location & Number",
		"`CommConsParticipate`.`ot_otherdetails`" => "Other details",
		"`CommConsParticipate`.`ot_comments`" => "Comments",
		"`CommConsParticipate`.`ot_SharedLink1`" => "Shared Link 1",
		"`CommConsParticipate`.`ot_SharedLink2`" => "Shared Link 2",
		"`CommConsParticipate`.`ot_Ref01`" => "Reference_1",
		"`CommConsParticipate`.`ot_Ref02`" => "Reference_2",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "Review",
		"`CommConsParticipate`.`ot_ap_RevComment`" => "Review Comment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "Approval",
		"`CommConsParticipate`.`ot_ap_ApprComment`" => "Approval Comment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "IMS Control",
		"`CommConsParticipate`.`ot_ap_QCComment`" => "IMS Control Comment",
		"`CommConsParticipate`.`ot_ap_filed`" => "Register",
		"`CommConsParticipate`.`ot_ap_lastmodified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`CommConsParticipate`.`id`" => "id",
		"`CommConsParticipate`.`ccpID`" => "ccpID",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, '; ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "WorkLocationID",
		"if(`CommConsParticipate`.`fo_WorkDate`,date_format(`CommConsParticipate`.`fo_WorkDate`,'%m/%d/%Y'),'')" => "fo_WorkDate",
		"if(`CommConsParticipate`.`fo_RequiredDate`,date_format(`CommConsParticipate`.`fo_RequiredDate`,'%m/%d/%Y'),'')" => "fo_RequiredDate",
		"CONCAT_WS('-', LEFT(`CommConsParticipate`.`ot_FileLoc`,3), MID(`CommConsParticipate`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`CommConsParticipate`.`ot_otherdetails`" => "ot_otherdetails",
		"`CommConsParticipate`.`ot_comments`" => "ot_comments",
		"`CommConsParticipate`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`CommConsParticipate`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`CommConsParticipate`.`ot_Ref01`" => "ot_Ref01",
		"`CommConsParticipate`.`ot_Ref02`" => "ot_Ref02",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`CommConsParticipate`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`CommConsParticipate`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`CommConsParticipate`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`CommConsParticipate`.`ot_ap_filed`, '%c/%e/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`CommConsParticipate`.`ot_ap_lastmodified`, '%c/%e/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'WorkLocationID' => 'Work Location', 'ot_ap_Review' => 'Review', 'ot_ap_Approval' => 'Approval', 'ot_ap_QC' => 'IMS Control');

	$x->QueryFrom = "`CommConsParticipate` LEFT JOIN `WorkLocation` as WorkLocation1 ON `WorkLocation1`.`id`=`CommConsParticipate`.`WorkLocationID` LEFT JOIN `Leadership` as Leadership1 ON `Leadership1`.`id`=`CommConsParticipate`.`ot_ap_Review` LEFT JOIN `Approval` as Approval1 ON `Approval1`.`id`=`CommConsParticipate`.`ot_ap_Approval` LEFT JOIN `IMSControl` as IMSControl1 ON `IMSControl1`.`id`=`CommConsParticipate`.`ot_ap_QC` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "CommConsParticipate_view.php";
	$x->RedirectAfterInsert = "CommConsParticipate_view.php?SelectedID=#ID#";
	$x->TableTitle = "Communication, Consultation & Participation";
	$x->TableIcon = "resources/table_icons/participation_rate.png";
	$x->PrimaryKey = "`CommConsParticipate`.`id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  75, 200, 100, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Communication Consulation & Participation ID", "Work Location", "Program Date", "End Date", "Review", "Approval", "IMS Control", "Register", "Last modified");
	$x->ColFieldName = array('ccpID', 'WorkLocationID', 'fo_WorkDate', 'fo_RequiredDate', 'ot_ap_Review', 'ot_ap_Approval', 'ot_ap_QC', 'ot_ap_filed', 'ot_ap_lastmodified');
	$x->ColNumber  = array(2, 3, 4, 5, 14, 16, 18, 20, 21);

	// template paths below are based on the app main directory
	$x->Template = 'templates/CommConsParticipate_templateTV.html';
	$x->SelectedTemplate = 'templates/CommConsParticipate_templateTVS.html';
	$x->TemplateDV = 'templates/CommConsParticipate_templateDV.html';
	$x->TemplateDVP = 'templates/CommConsParticipate_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `CommConsParticipate`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='CommConsParticipate' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `CommConsParticipate`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='CommConsParticipate' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`CommConsParticipate`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: CommConsParticipate_init
	$render=TRUE;
	if(function_exists('CommConsParticipate_init')){
		$args=array();
		$render=CommConsParticipate_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: CommConsParticipate_header
	$headerCode='';
	if(function_exists('CommConsParticipate_header')){
		$args=array();
		$headerCode=CommConsParticipate_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: CommConsParticipate_footer
	$footerCode='';
	if(function_exists('CommConsParticipate_footer')){
		$args=array();
		$footerCode=CommConsParticipate_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>