<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/employees.php");
	include("$currDir/employees_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('employees');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "employees";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`employees`.`EmployeeID`" => "EmployeeID",
		"`employees`.`EmpNo`" => "EmpNo",
		"`employees`.`Name`" => "Name",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, ': ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "BaseLocation",
		"`employees`.`fo_TermEmployment`" => "fo_TermEmployment",
		"`employees`.`fo_Photo`" => "fo_Photo",
		"`employees`.`fo_Position`" => "fo_Position",
		"if(`employees`.`fo_BirthDate`,date_format(`employees`.`fo_BirthDate`,'%m/%d/%Y'),'')" => "fo_BirthDate",
		"if(`employees`.`fo_HireDate`,date_format(`employees`.`fo_HireDate`,'%m/%d/%Y'),'')" => "fo_HireDate",
		"`employees`.`fo_Address`" => "fo_Address",
		"`employees`.`fo_City`" => "fo_City",
		"`employees`.`fo_Region`" => "fo_Region",
		"`employees`.`fo_PostalCode`" => "fo_PostalCode",
		"`employees`.`fo_Country`" => "fo_Country",
		"`employees`.`fo_HomePhone`" => "fo_HomePhone",
		"`employees`.`fo_Extension`" => "fo_Extension",
		"`employees`.`fo_Notes`" => "fo_Notes",
		"IF(    CHAR_LENGTH(`employees1`.`Name`) || CHAR_LENGTH(`employees1`.`EmployeeID`), CONCAT_WS('',   `employees1`.`Name`, ', ', `employees1`.`EmployeeID`), '') /* ReportsTo */" => "fo_ReportsTo",
		"concat('<img src=\"', if(`employees`.`fo_Acknowledgement`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "fo_Acknowledgement",
		"concat('<img src=\"', if(`employees`.`fo_Induction`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "fo_Induction",
		"CONCAT_WS('-', LEFT(`employees`.`ot_FileLoc`,3), MID(`employees`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`employees`.`ot_otherdetails`" => "ot_otherdetails",
		"`employees`.`ot_comments`" => "ot_comments",
		"`employees`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`employees`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`employees`.`ot_Ref01`" => "ot_Ref01",
		"`employees`.`ot_Ref02`" => "ot_Ref02",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`employees`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`employees`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`employees`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`employees`.`ot_ap_filed`, '%e/%c/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`employees`.`ot_ap_lastmodified`, '%e/%c/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`employees`.`EmployeeID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`employees`.`fo_BirthDate`',
		9 => '`employees`.`fo_HireDate`',
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => '`employees`.`fo_Acknowledgement`',
		20 => '`employees`.`fo_Induction`',
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => '`Leadership1`.`Status`',
		29 => 29,
		30 => '`Approval1`.`Status`',
		31 => 31,
		32 => '`IMSControl1`.`Status`',
		33 => 33,
		34 => '`employees`.`ot_ap_filed`',
		35 => '`employees`.`ot_ap_lastmodified`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`employees`.`EmployeeID`" => "EmployeeID",
		"`employees`.`EmpNo`" => "EmpNo",
		"`employees`.`Name`" => "Name",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, ': ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "BaseLocation",
		"`employees`.`fo_TermEmployment`" => "fo_TermEmployment",
		"`employees`.`fo_Photo`" => "fo_Photo",
		"`employees`.`fo_Position`" => "fo_Position",
		"if(`employees`.`fo_BirthDate`,date_format(`employees`.`fo_BirthDate`,'%m/%d/%Y'),'')" => "fo_BirthDate",
		"if(`employees`.`fo_HireDate`,date_format(`employees`.`fo_HireDate`,'%m/%d/%Y'),'')" => "fo_HireDate",
		"`employees`.`fo_Address`" => "fo_Address",
		"`employees`.`fo_City`" => "fo_City",
		"`employees`.`fo_Region`" => "fo_Region",
		"`employees`.`fo_PostalCode`" => "fo_PostalCode",
		"`employees`.`fo_Country`" => "fo_Country",
		"`employees`.`fo_HomePhone`" => "fo_HomePhone",
		"`employees`.`fo_Extension`" => "fo_Extension",
		"`employees`.`fo_Notes`" => "fo_Notes",
		"IF(    CHAR_LENGTH(`employees1`.`Name`) || CHAR_LENGTH(`employees1`.`EmployeeID`), CONCAT_WS('',   `employees1`.`Name`, ', ', `employees1`.`EmployeeID`), '') /* ReportsTo */" => "fo_ReportsTo",
		"`employees`.`fo_Acknowledgement`" => "fo_Acknowledgement",
		"`employees`.`fo_Induction`" => "fo_Induction",
		"CONCAT_WS('-', LEFT(`employees`.`ot_FileLoc`,3), MID(`employees`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`employees`.`ot_otherdetails`" => "ot_otherdetails",
		"`employees`.`ot_comments`" => "ot_comments",
		"`employees`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`employees`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`employees`.`ot_Ref01`" => "ot_Ref01",
		"`employees`.`ot_Ref02`" => "ot_Ref02",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`employees`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`employees`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`employees`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`employees`.`ot_ap_filed`, '%e/%c/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`employees`.`ot_ap_lastmodified`, '%e/%c/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`employees`.`EmployeeID`" => "Employee ID",
		"`employees`.`EmpNo`" => "Employee Number",
		"`employees`.`Name`" => "Full Name",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, ': ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "Work Location",
		"`employees`.`fo_TermEmployment`" => "Employment Term",
		"`employees`.`fo_Position`" => "Position",
		"`employees`.`fo_BirthDate`" => "Birth Date",
		"`employees`.`fo_HireDate`" => "Hire Date",
		"`employees`.`fo_Address`" => "Address",
		"`employees`.`fo_City`" => "City",
		"`employees`.`fo_Region`" => "Region",
		"`employees`.`fo_PostalCode`" => "Postal Code",
		"`employees`.`fo_Country`" => "Country",
		"`employees`.`fo_HomePhone`" => "Home Phone",
		"`employees`.`fo_Extension`" => "Extension",
		"`employees`.`fo_Notes`" => "Notes",
		"`employees`.`fo_Acknowledgement`" => "IMS Acknowledgement",
		"`employees`.`fo_Induction`" => "Awareness & Induction",
		"`employees`.`ot_FileLoc`" => "File Location & Number",
		"`employees`.`ot_otherdetails`" => "Other details",
		"`employees`.`ot_comments`" => "Comments",
		"`employees`.`ot_SharedLink1`" => "Shared Link 1",
		"`employees`.`ot_SharedLink2`" => "Shared Link 2",
		"`employees`.`ot_Ref01`" => "Reference_1",
		"`employees`.`ot_Ref02`" => "Reference_2",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "Review",
		"`employees`.`ot_ap_RevComment`" => "Review Comment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "Approval",
		"`employees`.`ot_ap_ApprComment`" => "Approval Comment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "IMS Control",
		"`employees`.`ot_ap_QCComment`" => "IMS Control Comment",
		"`employees`.`ot_ap_filed`" => "Register",
		"`employees`.`ot_ap_lastmodified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`employees`.`EmployeeID`" => "EmployeeID",
		"`employees`.`EmpNo`" => "EmpNo",
		"`employees`.`Name`" => "Name",
		"IF(    CHAR_LENGTH(`WorkLocation1`.`BaseLocation`) || CHAR_LENGTH(`WorkLocation1`.`DocItem`), CONCAT_WS('',   `WorkLocation1`.`BaseLocation`, ': ', `WorkLocation1`.`DocItem`), '') /* Work Location */" => "BaseLocation",
		"`employees`.`fo_TermEmployment`" => "fo_TermEmployment",
		"`employees`.`fo_Position`" => "fo_Position",
		"if(`employees`.`fo_BirthDate`,date_format(`employees`.`fo_BirthDate`,'%m/%d/%Y'),'')" => "fo_BirthDate",
		"if(`employees`.`fo_HireDate`,date_format(`employees`.`fo_HireDate`,'%m/%d/%Y'),'')" => "fo_HireDate",
		"`employees`.`fo_Address`" => "fo_Address",
		"`employees`.`fo_City`" => "fo_City",
		"`employees`.`fo_Region`" => "fo_Region",
		"`employees`.`fo_PostalCode`" => "fo_PostalCode",
		"`employees`.`fo_Country`" => "fo_Country",
		"`employees`.`fo_HomePhone`" => "fo_HomePhone",
		"`employees`.`fo_Extension`" => "fo_Extension",
		"`employees`.`fo_Notes`" => "fo_Notes",
		"concat('<img src=\"', if(`employees`.`fo_Acknowledgement`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "fo_Acknowledgement",
		"concat('<img src=\"', if(`employees`.`fo_Induction`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "fo_Induction",
		"CONCAT_WS('-', LEFT(`employees`.`ot_FileLoc`,3), MID(`employees`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`employees`.`ot_otherdetails`" => "ot_otherdetails",
		"`employees`.`ot_comments`" => "ot_comments",
		"`employees`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`employees`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`employees`.`ot_Ref01`" => "ot_Ref01",
		"`employees`.`ot_Ref02`" => "ot_Ref02",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`employees`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`employees`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`employees`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`employees`.`ot_ap_filed`, '%e/%c/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`employees`.`ot_ap_lastmodified`, '%e/%c/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'BaseLocation' => 'Work Location', 'fo_ReportsTo' => 'ReportsTo', 'ot_ap_Review' => 'Review', 'ot_ap_Approval' => 'Approval', 'ot_ap_QC' => 'IMS Control');

	$x->QueryFrom = "`employees` LEFT JOIN `WorkLocation` as WorkLocation1 ON `WorkLocation1`.`id`=`employees`.`BaseLocation` LEFT JOIN `employees` as employees1 ON `employees1`.`EmployeeID`=`employees`.`fo_ReportsTo` LEFT JOIN `Leadership` as Leadership1 ON `Leadership1`.`id`=`employees`.`ot_ap_Review` LEFT JOIN `Approval` as Approval1 ON `Approval1`.`id`=`employees`.`ot_ap_Approval` LEFT JOIN `IMSControl` as IMSControl1 ON `IMSControl1`.`id`=`employees`.`ot_ap_QC` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "employees_view.php";
	$x->RedirectAfterInsert = "employees_view.php";
	$x->TableTitle = "Human Resources Matrix";
	$x->TableIcon = "resources/table_icons/client_account_template.png";
	$x->PrimaryKey = "`employees`.`EmployeeID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 100, 200, 150, 60, 200, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Employee Number", "Full Name", "Work Location", "Employment Term", "Photo", "Position", "Review", "Approval", "IMS Control", "Register", "Last modified");
	$x->ColFieldName = array('EmpNo', 'Name', 'BaseLocation', 'fo_TermEmployment', 'fo_Photo', 'fo_Position', 'ot_ap_Review', 'ot_ap_Approval', 'ot_ap_QC', 'ot_ap_filed', 'ot_ap_lastmodified');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 28, 30, 32, 34, 35);

	// template paths below are based on the app main directory
	$x->Template = 'templates/employees_templateTV.html';
	$x->SelectedTemplate = 'templates/employees_templateTVS.html';
	$x->TemplateDV = 'templates/employees_templateDV.html';
	$x->TemplateDVP = 'templates/employees_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `employees`.`EmployeeID`=membership_userrecords.pkValue and membership_userrecords.tableName='employees' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `employees`.`EmployeeID`=membership_userrecords.pkValue and membership_userrecords.tableName='employees' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`employees`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: employees_init
	$render=TRUE;
	if(function_exists('employees_init')){
		$args=array();
		$render=employees_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: employees_header
	$headerCode='';
	if(function_exists('employees_header')){
		$args=array();
		$headerCode=employees_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: employees_footer
	$footerCode='';
	if(function_exists('employees_footer')){
		$args=array();
		$footerCode=employees_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>