<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/MRM.php");
	include("$currDir/MRM_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('MRM');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "MRM";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`MRM`.`id`" => "id",
		"`MRM`.`DocconNumber`" => "DocconNumber",
		"`MRM`.`DocItem`" => "DocItem",
		"`MRM`.`fo_DocumentDescription`" => "fo_DocumentDescription",
		"`MRM`.`fo_Classification`" => "fo_Classification",
		"`MRM`.`fo_Impact`" => "fo_Impact",
		"if(`MRM`.`fo_Regdate`,date_format(`MRM`.`fo_Regdate`,'%m/%d/%Y'),'')" => "fo_Regdate",
		"CONCAT_WS('-', LEFT(`MRM`.`ot_FileLoc`,3), MID(`MRM`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`MRM`.`ot_otherdetails`" => "ot_otherdetails",
		"`MRM`.`ot_comments`" => "ot_comments",
		"`MRM`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`MRM`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`MRM`.`ot_Ref01`" => "ot_Ref01",
		"`MRM`.`ot_Ref02`" => "ot_Ref02",
		"`MRM`.`ot_Ref03`" => "ot_Ref03",
		"`MRM`.`ot_Ref04`" => "ot_Ref04",
		"`MRM`.`ot_Ref05`" => "ot_Ref05",
		"`MRM`.`ot_Ref06`" => "ot_Ref06",
		"`MRM`.`ot_Photo01`" => "ot_Photo01",
		"`MRM`.`ot_Photo02`" => "ot_Photo02",
		"`MRM`.`ot_Photo03`" => "ot_Photo03",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`MRM`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`MRM`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`MRM`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"if(`MRM`.`ot_ap_filed`,date_format(`MRM`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`MRM`.`ot_ap_lastmodified`,date_format(`MRM`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`MRM`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`MRM`.`fo_Regdate`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => '`Leadership1`.`Status`',
		23 => 23,
		24 => '`Approval1`.`Status`',
		25 => 25,
		26 => '`IMSControl1`.`Status`',
		27 => 27,
		28 => '`MRM`.`ot_ap_filed`',
		29 => '`MRM`.`ot_ap_lastmodified`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`MRM`.`id`" => "id",
		"`MRM`.`DocconNumber`" => "DocconNumber",
		"`MRM`.`DocItem`" => "DocItem",
		"`MRM`.`fo_DocumentDescription`" => "fo_DocumentDescription",
		"`MRM`.`fo_Classification`" => "fo_Classification",
		"`MRM`.`fo_Impact`" => "fo_Impact",
		"if(`MRM`.`fo_Regdate`,date_format(`MRM`.`fo_Regdate`,'%m/%d/%Y'),'')" => "fo_Regdate",
		"CONCAT_WS('-', LEFT(`MRM`.`ot_FileLoc`,3), MID(`MRM`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`MRM`.`ot_otherdetails`" => "ot_otherdetails",
		"`MRM`.`ot_comments`" => "ot_comments",
		"`MRM`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`MRM`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`MRM`.`ot_Ref01`" => "ot_Ref01",
		"`MRM`.`ot_Ref02`" => "ot_Ref02",
		"`MRM`.`ot_Ref03`" => "ot_Ref03",
		"`MRM`.`ot_Ref04`" => "ot_Ref04",
		"`MRM`.`ot_Ref05`" => "ot_Ref05",
		"`MRM`.`ot_Ref06`" => "ot_Ref06",
		"`MRM`.`ot_Photo01`" => "ot_Photo01",
		"`MRM`.`ot_Photo02`" => "ot_Photo02",
		"`MRM`.`ot_Photo03`" => "ot_Photo03",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`MRM`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`MRM`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`MRM`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"if(`MRM`.`ot_ap_filed`,date_format(`MRM`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`MRM`.`ot_ap_lastmodified`,date_format(`MRM`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`MRM`.`id`" => "ID",
		"`MRM`.`DocconNumber`" => "Management Review Meeting ID",
		"`MRM`.`DocItem`" => "Title",
		"`MRM`.`fo_DocumentDescription`" => "Description",
		"`MRM`.`fo_Classification`" => "Classification",
		"`MRM`.`fo_Impact`" => "Direct Impact",
		"`MRM`.`fo_Regdate`" => "Register date",
		"`MRM`.`ot_FileLoc`" => "File Location & Number",
		"`MRM`.`ot_otherdetails`" => "Other details",
		"`MRM`.`ot_comments`" => "Comments",
		"`MRM`.`ot_SharedLink1`" => "Shared Link 1",
		"`MRM`.`ot_SharedLink2`" => "Shared Link 2",
		"`MRM`.`ot_Ref01`" => "Reference_1",
		"`MRM`.`ot_Ref02`" => "Reference_2",
		"`MRM`.`ot_Ref03`" => "Reference_3",
		"`MRM`.`ot_Ref04`" => "Reference_4",
		"`MRM`.`ot_Ref05`" => "Reference_5",
		"`MRM`.`ot_Ref06`" => "Reference_6",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "Review",
		"`MRM`.`ot_ap_RevComment`" => "Review Comment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "Approval",
		"`MRM`.`ot_ap_ApprComment`" => "Approval Comment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "IMS Control",
		"`MRM`.`ot_ap_QCComment`" => "IMS Control Comment",
		"`MRM`.`ot_ap_filed`" => "Register",
		"`MRM`.`ot_ap_lastmodified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`MRM`.`id`" => "id",
		"`MRM`.`DocconNumber`" => "DocconNumber",
		"`MRM`.`DocItem`" => "DocItem",
		"`MRM`.`fo_DocumentDescription`" => "fo_DocumentDescription",
		"`MRM`.`fo_Classification`" => "fo_Classification",
		"`MRM`.`fo_Impact`" => "fo_Impact",
		"if(`MRM`.`fo_Regdate`,date_format(`MRM`.`fo_Regdate`,'%m/%d/%Y'),'')" => "fo_Regdate",
		"CONCAT_WS('-', LEFT(`MRM`.`ot_FileLoc`,3), MID(`MRM`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`MRM`.`ot_otherdetails`" => "ot_otherdetails",
		"`MRM`.`ot_comments`" => "ot_comments",
		"`MRM`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`MRM`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`MRM`.`ot_Ref01`" => "ot_Ref01",
		"`MRM`.`ot_Ref02`" => "ot_Ref02",
		"`MRM`.`ot_Ref03`" => "ot_Ref03",
		"`MRM`.`ot_Ref04`" => "ot_Ref04",
		"`MRM`.`ot_Ref05`" => "ot_Ref05",
		"`MRM`.`ot_Ref06`" => "ot_Ref06",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`MRM`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`MRM`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`MRM`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"if(`MRM`.`ot_ap_filed`,date_format(`MRM`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`MRM`.`ot_ap_lastmodified`,date_format(`MRM`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'ot_ap_Review' => 'Review', 'ot_ap_Approval' => 'Approval', 'ot_ap_QC' => 'IMS Control');

	$x->QueryFrom = "`MRM` LEFT JOIN `Leadership` as Leadership1 ON `Leadership1`.`id`=`MRM`.`ot_ap_Review` LEFT JOIN `Approval` as Approval1 ON `Approval1`.`id`=`MRM`.`ot_ap_Approval` LEFT JOIN `IMSControl` as IMSControl1 ON `IMSControl1`.`id`=`MRM`.`ot_ap_QC` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "MRM_view.php";
	$x->RedirectAfterInsert = "MRM_view.php?SelectedID=#ID#";
	$x->TableTitle = "Management Review Meeting";
	$x->TableIcon = "resources/table_icons/attach.png";
	$x->PrimaryKey = "`MRM`.`id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  120, 120, 70, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Management Review Meeting ID", "Title", "Classification", "Direct Impact", "Register date", "Review", "Approval", "IMS Control", "Register", "Last modified");
	$x->ColFieldName = array('DocconNumber', 'DocItem', 'fo_Classification', 'fo_Impact', 'fo_Regdate', 'ot_ap_Review', 'ot_ap_Approval', 'ot_ap_QC', 'ot_ap_filed', 'ot_ap_lastmodified');
	$x->ColNumber  = array(2, 3, 5, 6, 7, 22, 24, 26, 28, 29);

	// template paths below are based on the app main directory
	$x->Template = 'templates/MRM_templateTV.html';
	$x->SelectedTemplate = 'templates/MRM_templateTVS.html';
	$x->TemplateDV = 'templates/MRM_templateDV.html';
	$x->TemplateDVP = 'templates/MRM_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `MRM`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='MRM' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `MRM`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='MRM' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`MRM`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: MRM_init
	$render=TRUE;
	if(function_exists('MRM_init')){
		$args=array();
		$render=MRM_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: MRM_header
	$headerCode='';
	if(function_exists('MRM_header')){
		$args=array();
		$headerCode=MRM_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: MRM_footer
	$footerCode='';
	if(function_exists('MRM_footer')){
		$args=array();
		$footerCode=MRM_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>