<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/MWOpreventive.php");
	include("$currDir/MWOpreventive_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('MWOpreventive');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "MWOpreventive";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`MWOpreventive`.`id`" => "id",
		"`MWOpreventive`.`PreventiveID`" => "PreventiveID",
		"IF(    CHAR_LENGTH(`MWO1`.`MWONumber`), CONCAT_WS('',   `MWO1`.`MWONumber`), '') /* MWO ID */" => "MwoID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpNo`) || CHAR_LENGTH(`employees1`.`Name`), CONCAT_WS('',   `employees1`.`EmpNo`, '; ', `employees1`.`Name`), '') /* Employee Name */" => "fo_EmployeeID",
		"IF(    CHAR_LENGTH(`employees1`.`fo_Position`), CONCAT_WS('',   `employees1`.`fo_Position`), '') /* Position */" => "fo_Position",
		"CONCAT_WS('-', LEFT(`MWOpreventive`.`ot_FileLoc`,3), MID(`MWOpreventive`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`MWOpreventive`.`ot_otherdetails`" => "ot_otherdetails",
		"`MWOpreventive`.`ot_comments`" => "ot_comments",
		"`MWOpreventive`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`MWOpreventive`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`MWOpreventive`.`ot_Ref01`" => "ot_Ref01",
		"`MWOpreventive`.`ot_Ref02`" => "ot_Ref02",
		"`MWOpreventive`.`ot_Ref03`" => "ot_Ref03",
		"`MWOpreventive`.`ot_Ref04`" => "ot_Ref04",
		"`MWOpreventive`.`ot_Ref05`" => "ot_Ref05",
		"`MWOpreventive`.`ot_Ref06`" => "ot_Ref06",
		"`MWOpreventive`.`ot_Photo01`" => "ot_Photo01",
		"`MWOpreventive`.`ot_Photo02`" => "ot_Photo02",
		"`MWOpreventive`.`ot_Photo03`" => "ot_Photo03",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`MWOpreventive`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`MWOpreventive`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`MWOpreventive`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"if(`MWOpreventive`.`ot_ap_filed`,date_format(`MWOpreventive`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`MWOpreventive`.`ot_ap_lastmodified`,date_format(`MWOpreventive`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`MWOpreventive`.`id`',
		2 => 2,
		3 => '`MWO1`.`MWONumber`',
		4 => 4,
		5 => '`employees1`.`fo_Position`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => '`Leadership1`.`Status`',
		21 => 21,
		22 => '`Approval1`.`Status`',
		23 => 23,
		24 => '`IMSControl1`.`Status`',
		25 => 25,
		26 => '`MWOpreventive`.`ot_ap_filed`',
		27 => '`MWOpreventive`.`ot_ap_lastmodified`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`MWOpreventive`.`id`" => "id",
		"`MWOpreventive`.`PreventiveID`" => "PreventiveID",
		"IF(    CHAR_LENGTH(`MWO1`.`MWONumber`), CONCAT_WS('',   `MWO1`.`MWONumber`), '') /* MWO ID */" => "MwoID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpNo`) || CHAR_LENGTH(`employees1`.`Name`), CONCAT_WS('',   `employees1`.`EmpNo`, '; ', `employees1`.`Name`), '') /* Employee Name */" => "fo_EmployeeID",
		"IF(    CHAR_LENGTH(`employees1`.`fo_Position`), CONCAT_WS('',   `employees1`.`fo_Position`), '') /* Position */" => "fo_Position",
		"CONCAT_WS('-', LEFT(`MWOpreventive`.`ot_FileLoc`,3), MID(`MWOpreventive`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`MWOpreventive`.`ot_otherdetails`" => "ot_otherdetails",
		"`MWOpreventive`.`ot_comments`" => "ot_comments",
		"`MWOpreventive`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`MWOpreventive`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`MWOpreventive`.`ot_Ref01`" => "ot_Ref01",
		"`MWOpreventive`.`ot_Ref02`" => "ot_Ref02",
		"`MWOpreventive`.`ot_Ref03`" => "ot_Ref03",
		"`MWOpreventive`.`ot_Ref04`" => "ot_Ref04",
		"`MWOpreventive`.`ot_Ref05`" => "ot_Ref05",
		"`MWOpreventive`.`ot_Ref06`" => "ot_Ref06",
		"`MWOpreventive`.`ot_Photo01`" => "ot_Photo01",
		"`MWOpreventive`.`ot_Photo02`" => "ot_Photo02",
		"`MWOpreventive`.`ot_Photo03`" => "ot_Photo03",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`MWOpreventive`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`MWOpreventive`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`MWOpreventive`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"if(`MWOpreventive`.`ot_ap_filed`,date_format(`MWOpreventive`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`MWOpreventive`.`ot_ap_lastmodified`,date_format(`MWOpreventive`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`MWOpreventive`.`id`" => "ID",
		"`MWOpreventive`.`PreventiveID`" => "Preventive MWO Record Number",
		"IF(    CHAR_LENGTH(`MWO1`.`MWONumber`), CONCAT_WS('',   `MWO1`.`MWONumber`), '') /* MWO ID */" => "MWO ID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpNo`) || CHAR_LENGTH(`employees1`.`Name`), CONCAT_WS('',   `employees1`.`EmpNo`, '; ', `employees1`.`Name`), '') /* Employee Name */" => "Employee Name",
		"IF(    CHAR_LENGTH(`employees1`.`fo_Position`), CONCAT_WS('',   `employees1`.`fo_Position`), '') /* Position */" => "Position",
		"`MWOpreventive`.`ot_FileLoc`" => "File Location & Number",
		"`MWOpreventive`.`ot_otherdetails`" => "Other details",
		"`MWOpreventive`.`ot_comments`" => "Comments",
		"`MWOpreventive`.`ot_SharedLink1`" => "Shared Link 1",
		"`MWOpreventive`.`ot_SharedLink2`" => "Shared Link 2",
		"`MWOpreventive`.`ot_Ref01`" => "Reference_1",
		"`MWOpreventive`.`ot_Ref02`" => "Reference_2",
		"`MWOpreventive`.`ot_Ref03`" => "Reference_3",
		"`MWOpreventive`.`ot_Ref04`" => "Reference_4",
		"`MWOpreventive`.`ot_Ref05`" => "Reference_5",
		"`MWOpreventive`.`ot_Ref06`" => "Reference_6",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "Review",
		"`MWOpreventive`.`ot_ap_RevComment`" => "Review Comment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "Approval",
		"`MWOpreventive`.`ot_ap_ApprComment`" => "Approval Comment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "IMS Control",
		"`MWOpreventive`.`ot_ap_QCComment`" => "IMS Control Comment",
		"`MWOpreventive`.`ot_ap_filed`" => "Register",
		"`MWOpreventive`.`ot_ap_lastmodified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`MWOpreventive`.`id`" => "id",
		"`MWOpreventive`.`PreventiveID`" => "PreventiveID",
		"IF(    CHAR_LENGTH(`MWO1`.`MWONumber`), CONCAT_WS('',   `MWO1`.`MWONumber`), '') /* MWO ID */" => "MwoID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpNo`) || CHAR_LENGTH(`employees1`.`Name`), CONCAT_WS('',   `employees1`.`EmpNo`, '; ', `employees1`.`Name`), '') /* Employee Name */" => "fo_EmployeeID",
		"IF(    CHAR_LENGTH(`employees1`.`fo_Position`), CONCAT_WS('',   `employees1`.`fo_Position`), '') /* Position */" => "fo_Position",
		"CONCAT_WS('-', LEFT(`MWOpreventive`.`ot_FileLoc`,3), MID(`MWOpreventive`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`MWOpreventive`.`ot_otherdetails`" => "ot_otherdetails",
		"`MWOpreventive`.`ot_comments`" => "ot_comments",
		"`MWOpreventive`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`MWOpreventive`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`MWOpreventive`.`ot_Ref01`" => "ot_Ref01",
		"`MWOpreventive`.`ot_Ref02`" => "ot_Ref02",
		"`MWOpreventive`.`ot_Ref03`" => "ot_Ref03",
		"`MWOpreventive`.`ot_Ref04`" => "ot_Ref04",
		"`MWOpreventive`.`ot_Ref05`" => "ot_Ref05",
		"`MWOpreventive`.`ot_Ref06`" => "ot_Ref06",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`MWOpreventive`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`MWOpreventive`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`MWOpreventive`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"if(`MWOpreventive`.`ot_ap_filed`,date_format(`MWOpreventive`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`MWOpreventive`.`ot_ap_lastmodified`,date_format(`MWOpreventive`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'MwoID' => 'MWO ID', 'fo_EmployeeID' => 'Employee Name', 'ot_ap_Review' => 'Review', 'ot_ap_Approval' => 'Approval', 'ot_ap_QC' => 'IMS Control');

	$x->QueryFrom = "`MWOpreventive` LEFT JOIN `MWO` as MWO1 ON `MWO1`.`id`=`MWOpreventive`.`MwoID` LEFT JOIN `employees` as employees1 ON `employees1`.`EmployeeID`=`MWOpreventive`.`fo_EmployeeID` LEFT JOIN `Leadership` as Leadership1 ON `Leadership1`.`id`=`MWOpreventive`.`ot_ap_Review` LEFT JOIN `Approval` as Approval1 ON `Approval1`.`id`=`MWOpreventive`.`ot_ap_Approval` LEFT JOIN `IMSControl` as IMSControl1 ON `IMSControl1`.`id`=`MWOpreventive`.`ot_ap_QC` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "MWOpreventive_view.php";
	$x->RedirectAfterInsert = "MWOpreventive_view.php?SelectedID=#ID#";
	$x->TableTitle = "Preventive";
	$x->TableIcon = "resources/table_icons/application_form_magnify.png";
	$x->PrimaryKey = "`MWOpreventive`.`id`";
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 70, 120, 120, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Preventive MWO Record Number", "MWO ID", "Employee Name", "Position", "Review", "Approval", "IMS Control", "Register", "Last modified");
	$x->ColFieldName = array('PreventiveID', 'MwoID', 'fo_EmployeeID', 'fo_Position', 'ot_ap_Review', 'ot_ap_Approval', 'ot_ap_QC', 'ot_ap_filed', 'ot_ap_lastmodified');
	$x->ColNumber  = array(2, 3, 4, 5, 20, 22, 24, 26, 27);

	// template paths below are based on the app main directory
	$x->Template = 'templates/MWOpreventive_templateTV.html';
	$x->SelectedTemplate = 'templates/MWOpreventive_templateTVS.html';
	$x->TemplateDV = 'templates/MWOpreventive_templateDV.html';
	$x->TemplateDVP = 'templates/MWOpreventive_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `MWOpreventive`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='MWOpreventive' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `MWOpreventive`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='MWOpreventive' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`MWOpreventive`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: MWOpreventive_init
	$render=TRUE;
	if(function_exists('MWOpreventive_init')){
		$args=array();
		$render=MWOpreventive_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: MWOpreventive_header
	$headerCode='';
	if(function_exists('MWOpreventive_header')){
		$args=array();
		$headerCode=MWOpreventive_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: MWOpreventive_footer
	$footerCode='';
	if(function_exists('MWOpreventive_footer')){
		$args=array();
		$footerCode=MWOpreventive_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>