<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/transactions.php");
	include("$currDir/transactions_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('transactions');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "transactions";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`transactions`.`id`" => "id",
		"`transactions`.`TransCode`" => "TransCode",
		"if(`transactions`.`fo_transaction_date`,date_format(`transactions`.`fo_transaction_date`,'%m/%d/%Y'),'')" => "fo_transaction_date",
		"IF(    CHAR_LENGTH(`Item1`.`ItemID`) || CHAR_LENGTH(`Item1`.`ProductName`), CONCAT_WS('',   `Item1`.`ItemID`, '::', `Item1`.`ProductName`), '') /* Item */" => "fo_item",
		"IF(    CHAR_LENGTH(`resources1`.`ResourcesID`) || CHAR_LENGTH(`resources1`.`Name`), CONCAT_WS('',   `resources1`.`ResourcesID`, '::', `resources1`.`Name`), '') /* Resources ID */" => "fo_ResourcesID",
		"`transactions`.`fo_transactiontype`" => "fo_transactiontype",
		"`transactions`.`fo_quantity`" => "fo_quantity",
		"`transactions`.`ot_FileLoc`" => "ot_FileLoc",
		"`transactions`.`ot_otherdetails`" => "ot_otherdetails",
		"`transactions`.`ot_comments`" => "ot_comments",
		"`transactions`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`transactions`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`transactions`.`ot_Ref01`" => "ot_Ref01",
		"`transactions`.`ot_Ref02`" => "ot_Ref02",
		"`transactions`.`ot_Ref03`" => "ot_Ref03",
		"`transactions`.`ot_Ref04`" => "ot_Ref04",
		"`transactions`.`ot_Ref05`" => "ot_Ref05",
		"`transactions`.`ot_Ref06`" => "ot_Ref06",
		"`transactions`.`ot_Photo01`" => "ot_Photo01",
		"`transactions`.`ot_Photo02`" => "ot_Photo02",
		"`transactions`.`ot_Photo03`" => "ot_Photo03",
		"if(`transactions`.`ot_ap_filed`,date_format(`transactions`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`transactions`.`ot_ap_lastmodified`,date_format(`transactions`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`transactions`.`id`',
		2 => 2,
		3 => '`transactions`.`fo_transaction_date`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`transactions`.`fo_quantity`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => '`transactions`.`ot_ap_filed`',
		23 => '`transactions`.`ot_ap_lastmodified`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`transactions`.`id`" => "id",
		"`transactions`.`TransCode`" => "TransCode",
		"if(`transactions`.`fo_transaction_date`,date_format(`transactions`.`fo_transaction_date`,'%m/%d/%Y'),'')" => "fo_transaction_date",
		"IF(    CHAR_LENGTH(`Item1`.`ItemID`) || CHAR_LENGTH(`Item1`.`ProductName`), CONCAT_WS('',   `Item1`.`ItemID`, '::', `Item1`.`ProductName`), '') /* Item */" => "fo_item",
		"IF(    CHAR_LENGTH(`resources1`.`ResourcesID`) || CHAR_LENGTH(`resources1`.`Name`), CONCAT_WS('',   `resources1`.`ResourcesID`, '::', `resources1`.`Name`), '') /* Resources ID */" => "fo_ResourcesID",
		"`transactions`.`fo_transactiontype`" => "fo_transactiontype",
		"`transactions`.`fo_quantity`" => "fo_quantity",
		"`transactions`.`ot_FileLoc`" => "ot_FileLoc",
		"`transactions`.`ot_otherdetails`" => "ot_otherdetails",
		"`transactions`.`ot_comments`" => "ot_comments",
		"`transactions`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`transactions`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`transactions`.`ot_Ref01`" => "ot_Ref01",
		"`transactions`.`ot_Ref02`" => "ot_Ref02",
		"`transactions`.`ot_Ref03`" => "ot_Ref03",
		"`transactions`.`ot_Ref04`" => "ot_Ref04",
		"`transactions`.`ot_Ref05`" => "ot_Ref05",
		"`transactions`.`ot_Ref06`" => "ot_Ref06",
		"`transactions`.`ot_Photo01`" => "ot_Photo01",
		"`transactions`.`ot_Photo02`" => "ot_Photo02",
		"`transactions`.`ot_Photo03`" => "ot_Photo03",
		"if(`transactions`.`ot_ap_filed`,date_format(`transactions`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`transactions`.`ot_ap_lastmodified`,date_format(`transactions`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`transactions`.`id`" => "ID",
		"`transactions`.`TransCode`" => "Transation ID",
		"`transactions`.`fo_transaction_date`" => "Transaction date",
		"IF(    CHAR_LENGTH(`Item1`.`ItemID`) || CHAR_LENGTH(`Item1`.`ProductName`), CONCAT_WS('',   `Item1`.`ItemID`, '::', `Item1`.`ProductName`), '') /* Item */" => "Item",
		"IF(    CHAR_LENGTH(`resources1`.`ResourcesID`) || CHAR_LENGTH(`resources1`.`Name`), CONCAT_WS('',   `resources1`.`ResourcesID`, '::', `resources1`.`Name`), '') /* Resources ID */" => "Resources ID",
		"`transactions`.`fo_transactiontype`" => "Transaction type",
		"`transactions`.`fo_quantity`" => "Quantity",
		"`transactions`.`ot_FileLoc`" => "File Location & Number",
		"`transactions`.`ot_otherdetails`" => "Other details",
		"`transactions`.`ot_comments`" => "Comments",
		"`transactions`.`ot_SharedLink1`" => "Shared Link 1",
		"`transactions`.`ot_SharedLink2`" => "Shared Link 2",
		"`transactions`.`ot_Ref01`" => "Reference_1",
		"`transactions`.`ot_Ref02`" => "Reference_2",
		"`transactions`.`ot_Ref03`" => "Reference_3",
		"`transactions`.`ot_Ref04`" => "Reference_4",
		"`transactions`.`ot_Ref05`" => "Reference_5",
		"`transactions`.`ot_Ref06`" => "Reference_6",
		"`transactions`.`ot_ap_filed`" => "Filed",
		"`transactions`.`ot_ap_lastmodified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`transactions`.`id`" => "id",
		"`transactions`.`TransCode`" => "TransCode",
		"if(`transactions`.`fo_transaction_date`,date_format(`transactions`.`fo_transaction_date`,'%m/%d/%Y'),'')" => "fo_transaction_date",
		"IF(    CHAR_LENGTH(`Item1`.`ItemID`) || CHAR_LENGTH(`Item1`.`ProductName`), CONCAT_WS('',   `Item1`.`ItemID`, '::', `Item1`.`ProductName`), '') /* Item */" => "fo_item",
		"IF(    CHAR_LENGTH(`resources1`.`ResourcesID`) || CHAR_LENGTH(`resources1`.`Name`), CONCAT_WS('',   `resources1`.`ResourcesID`, '::', `resources1`.`Name`), '') /* Resources ID */" => "fo_ResourcesID",
		"`transactions`.`fo_transactiontype`" => "fo_transactiontype",
		"`transactions`.`fo_quantity`" => "fo_quantity",
		"`transactions`.`ot_FileLoc`" => "ot_FileLoc",
		"`transactions`.`ot_otherdetails`" => "ot_otherdetails",
		"`transactions`.`ot_comments`" => "ot_comments",
		"`transactions`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`transactions`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`transactions`.`ot_Ref01`" => "ot_Ref01",
		"`transactions`.`ot_Ref02`" => "ot_Ref02",
		"`transactions`.`ot_Ref03`" => "ot_Ref03",
		"`transactions`.`ot_Ref04`" => "ot_Ref04",
		"`transactions`.`ot_Ref05`" => "ot_Ref05",
		"`transactions`.`ot_Ref06`" => "ot_Ref06",
		"if(`transactions`.`ot_ap_filed`,date_format(`transactions`.`ot_ap_filed`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_filed",
		"if(`transactions`.`ot_ap_lastmodified`,date_format(`transactions`.`ot_ap_lastmodified`,'%m/%d/%Y %h:%i %p'),'')" => "ot_ap_lastmodified"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'fo_item' => 'Item', 'fo_ResourcesID' => 'Resources ID');

	$x->QueryFrom = "`transactions` LEFT JOIN `Item` as Item1 ON `Item1`.`ProductID`=`transactions`.`fo_item` LEFT JOIN `resources` as resources1 ON `resources1`.`Id`=`transactions`.`fo_ResourcesID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "transactions_view.php";
	$x->RedirectAfterInsert = "transactions_view.php?SelectedID=#ID#";
	$x->TableTitle = "Transfer Item";
	$x->TableIcon = "resources/table_icons/book_keeping.png";
	$x->PrimaryKey = "`transactions`.`id`";
	$x->DefaultSortField = '`transactions`.`fo_transaction_date`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Transation ID", "Transaction date", "Item", "Resources ID", "Transaction type", "Filed", "Last modified");
	$x->ColFieldName = array('TransCode', 'fo_transaction_date', 'fo_item', 'fo_ResourcesID', 'fo_transactiontype', 'ot_ap_filed', 'ot_ap_lastmodified');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 22, 23);

	// template paths below are based on the app main directory
	$x->Template = 'templates/transactions_templateTV.html';
	$x->SelectedTemplate = 'templates/transactions_templateTVS.html';
	$x->TemplateDV = 'templates/transactions_templateDV.html';
	$x->TemplateDVP = 'templates/transactions_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transactions`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transactions' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transactions`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transactions' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`transactions`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: transactions_init
	$render=TRUE;
	if(function_exists('transactions_init')){
		$args=array();
		$render=transactions_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: transactions_header
	$headerCode='';
	if(function_exists('transactions_header')){
		$args=array();
		$headerCode=transactions_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: transactions_footer
	$footerCode='';
	if(function_exists('transactions_footer')){
		$args=array();
		$footerCode=transactions_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>