<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/DocControl.php");
	include("$currDir/DocControl_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('DocControl');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "DocControl";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`DocControl`.`id`" => "id",
		"`DocControl`.`DocconNumber`" => "DocconNumber",
		"`DocControl`.`DocItem`" => "DocItem",
		"`DocControl`.`fo_DocumentDescription`" => "fo_DocumentDescription",
		"`DocControl`.`fo_Class`" => "fo_Class",
		"`DocControl`.`fo_DocumentType`" => "fo_DocumentType",
		"`DocControl`.`fo_Rev`" => "fo_Rev",
		"if(`DocControl`.`fo_date`,date_format(`DocControl`.`fo_date`,'%m/%d/%Y'),'')" => "fo_date",
		"CONCAT_WS('-', LEFT(`DocControl`.`ot_FileLoc`,3), MID(`DocControl`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`DocControl`.`ot_otherdetails`" => "ot_otherdetails",
		"`DocControl`.`ot_comments`" => "ot_comments",
		"`DocControl`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`DocControl`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`DocControl`.`ot_Ref01`" => "ot_Ref01",
		"`DocControl`.`ot_Ref02`" => "ot_Ref02",
		"`DocControl`.`ot_Photo`" => "ot_Photo",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`DocControl`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`DocControl`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`DocControl`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`DocControl`.`ot_ap_filed`, '%c/%e/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`DocControl`.`ot_ap_lastmodified`, '%c/%e/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`DocControl`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`DocControl`.`fo_date`',
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => '`Leadership1`.`Status`',
		18 => 18,
		19 => '`Approval1`.`Status`',
		20 => 20,
		21 => '`IMSControl1`.`Status`',
		22 => 22,
		23 => '`DocControl`.`ot_ap_filed`',
		24 => '`DocControl`.`ot_ap_lastmodified`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`DocControl`.`id`" => "id",
		"`DocControl`.`DocconNumber`" => "DocconNumber",
		"`DocControl`.`DocItem`" => "DocItem",
		"`DocControl`.`fo_DocumentDescription`" => "fo_DocumentDescription",
		"`DocControl`.`fo_Class`" => "fo_Class",
		"`DocControl`.`fo_DocumentType`" => "fo_DocumentType",
		"`DocControl`.`fo_Rev`" => "fo_Rev",
		"if(`DocControl`.`fo_date`,date_format(`DocControl`.`fo_date`,'%m/%d/%Y'),'')" => "fo_date",
		"CONCAT_WS('-', LEFT(`DocControl`.`ot_FileLoc`,3), MID(`DocControl`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`DocControl`.`ot_otherdetails`" => "ot_otherdetails",
		"`DocControl`.`ot_comments`" => "ot_comments",
		"`DocControl`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`DocControl`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`DocControl`.`ot_Ref01`" => "ot_Ref01",
		"`DocControl`.`ot_Ref02`" => "ot_Ref02",
		"`DocControl`.`ot_Photo`" => "ot_Photo",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`DocControl`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`DocControl`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`DocControl`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`DocControl`.`ot_ap_filed`, '%c/%e/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`DocControl`.`ot_ap_lastmodified`, '%c/%e/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`DocControl`.`id`" => "ID",
		"`DocControl`.`DocconNumber`" => "Document Number",
		"`DocControl`.`DocItem`" => "Title",
		"`DocControl`.`fo_DocumentDescription`" => "Description",
		"`DocControl`.`fo_Class`" => "Classification",
		"`DocControl`.`fo_DocumentType`" => "Document Type",
		"`DocControl`.`fo_Rev`" => "Revision",
		"`DocControl`.`fo_date`" => "Effective date",
		"`DocControl`.`ot_FileLoc`" => "File Location & Number",
		"`DocControl`.`ot_otherdetails`" => "Other details",
		"`DocControl`.`ot_comments`" => "Comments",
		"`DocControl`.`ot_SharedLink1`" => "Shared Link 1",
		"`DocControl`.`ot_SharedLink2`" => "Shared Link 2",
		"`DocControl`.`ot_Ref01`" => "Reference_1",
		"`DocControl`.`ot_Ref02`" => "Reference_2",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "Review",
		"`DocControl`.`ot_ap_RevComment`" => "Review Comment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "Approval",
		"`DocControl`.`ot_ap_ApprComment`" => "Approval Comment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "IMS Control",
		"`DocControl`.`ot_ap_QCComment`" => "IMS Control Comment",
		"`DocControl`.`ot_ap_filed`" => "Register",
		"`DocControl`.`ot_ap_lastmodified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`DocControl`.`id`" => "id",
		"`DocControl`.`DocconNumber`" => "DocconNumber",
		"`DocControl`.`DocItem`" => "DocItem",
		"`DocControl`.`fo_DocumentDescription`" => "fo_DocumentDescription",
		"`DocControl`.`fo_Class`" => "fo_Class",
		"`DocControl`.`fo_DocumentType`" => "fo_DocumentType",
		"`DocControl`.`fo_Rev`" => "fo_Rev",
		"if(`DocControl`.`fo_date`,date_format(`DocControl`.`fo_date`,'%m/%d/%Y'),'')" => "fo_date",
		"CONCAT_WS('-', LEFT(`DocControl`.`ot_FileLoc`,3), MID(`DocControl`.`ot_FileLoc`,4,3))" => "ot_FileLoc",
		"`DocControl`.`ot_otherdetails`" => "ot_otherdetails",
		"`DocControl`.`ot_comments`" => "ot_comments",
		"`DocControl`.`ot_SharedLink1`" => "ot_SharedLink1",
		"`DocControl`.`ot_SharedLink2`" => "ot_SharedLink2",
		"`DocControl`.`ot_Ref01`" => "ot_Ref01",
		"`DocControl`.`ot_Ref02`" => "ot_Ref02",
		"IF(    CHAR_LENGTH(`Leadership1`.`Status`), CONCAT_WS('',   `Leadership1`.`Status`), '') /* Review */" => "ot_ap_Review",
		"`DocControl`.`ot_ap_RevComment`" => "ot_ap_RevComment",
		"IF(    CHAR_LENGTH(`Approval1`.`Status`), CONCAT_WS('',   `Approval1`.`Status`), '') /* Approval */" => "ot_ap_Approval",
		"`DocControl`.`ot_ap_ApprComment`" => "ot_ap_ApprComment",
		"IF(    CHAR_LENGTH(`IMSControl1`.`Status`), CONCAT_WS('',   `IMSControl1`.`Status`), '') /* IMS Control */" => "ot_ap_QC",
		"`DocControl`.`ot_ap_QCComment`" => "ot_ap_QCComment",
		"DATE_FORMAT(`DocControl`.`ot_ap_filed`, '%c/%e/%Y %l:%i%p')" => "ot_ap_filed",
		"DATE_FORMAT(`DocControl`.`ot_ap_lastmodified`, '%c/%e/%Y %l:%i%p')" => "ot_ap_lastmodified"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'ot_ap_Review' => 'Review', 'ot_ap_Approval' => 'Approval', 'ot_ap_QC' => 'IMS Control');

	$x->QueryFrom = "`DocControl` LEFT JOIN `Leadership` as Leadership1 ON `Leadership1`.`id`=`DocControl`.`ot_ap_Review` LEFT JOIN `Approval` as Approval1 ON `Approval1`.`id`=`DocControl`.`ot_ap_Approval` LEFT JOIN `IMSControl` as IMSControl1 ON `IMSControl1`.`id`=`DocControl`.`ot_ap_QC` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "DocControl_view.php";
	$x->RedirectAfterInsert = "DocControl_view.php";
	$x->TableTitle = "Document & Record Control";
	$x->TableIcon = "resources/table_icons/application_error.png";
	$x->PrimaryKey = "`DocControl`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  120, 120, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Document Number", "Title", "Classification", "Document Type", "Revision", "Effective date", "Review", "Approval", "IMS Control", "Register", "Last modified");
	$x->ColFieldName = array('DocconNumber', 'DocItem', 'fo_Class', 'fo_DocumentType', 'fo_Rev', 'fo_date', 'ot_ap_Review', 'ot_ap_Approval', 'ot_ap_QC', 'ot_ap_filed', 'ot_ap_lastmodified');
	$x->ColNumber  = array(2, 3, 5, 6, 7, 8, 17, 19, 21, 23, 24);

	// template paths below are based on the app main directory
	$x->Template = 'templates/DocControl_templateTV.html';
	$x->SelectedTemplate = 'templates/DocControl_templateTVS.html';
	$x->TemplateDV = 'templates/DocControl_templateDV.html';
	$x->TemplateDVP = 'templates/DocControl_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `DocControl`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='DocControl' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `DocControl`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='DocControl' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`DocControl`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: DocControl_init
	$render=TRUE;
	if(function_exists('DocControl_init')){
		$args=array();
		$render=DocControl_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: DocControl_header
	$headerCode='';
	if(function_exists('DocControl_header')){
		$args=array();
		$headerCode=DocControl_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: DocControl_footer
	$footerCode='';
	if(function_exists('DocControl_footer')){
		$args=array();
		$footerCode=DocControl_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>