<?php
	// check this file's MD5 to make sure it wasn't called before
	$prevMD5=@implode('', @file(dirname(__FILE__).'/setup.md5'));
	$thisMD5=md5(@implode('', @file("./updateDB.php")));
	if($thisMD5==$prevMD5){
		$setupAlreadyRun=true;
	}else{
		// set up tables
		if(!isset($silent)){
			$silent=true;
		}

		// set up tables
		setupTable('OrgContentContext', "create table if not exists `OrgContentContext` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RecordNumber` VARCHAR(250) not null , unique `RecordNumber_unique` (`RecordNumber`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Type` VARCHAR(250) not null default 'Unknown' , `fo_genrec` VARCHAR(256) not null , `fo_Update` VARCHAR(256) , `fo_DateUpload` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('OrgContentContext', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Marketing', "create table if not exists `Marketing` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RecordNumber` VARCHAR(250) not null , unique `RecordNumber_unique` (`RecordNumber`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Type` VARCHAR(250) not null default 'Unknown' , `fo_Source` VARCHAR(256) not null , `fo_Qualification` VARCHAR(256) , `fo_DateUpload` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Marketing', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Client', "create table if not exists `Client` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ClientID` VARCHAR(250) not null , unique `ClientID_unique` (`ClientID`), `CompanyName` VARCHAR(255) , `fo_ContactName` VARCHAR(200) , `fo_ContactTitle` VARCHAR(200) , `fo_Address` VARCHAR(250) , `fo_City` VARCHAR(100) , `fo_Region` VARCHAR(100) , `fo_PostalCode` VARCHAR(10) , `fo_Country` VARCHAR(15) , `fo_Phone` VARCHAR(24) , `fo_Fax` VARCHAR(24) , `fo_Email` VARCHAR(80) , `ot_FileLoc` VARCHAR(100) , `ot_otherDetails` TEXT , `ot_Comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Client', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Inquiry', "create table if not exists `Inquiry` (   `id` INT unsigned not null auto_increment , primary key (`id`), `InqNumber` VARCHAR(100) not null , unique `InqNumber_unique` (`InqNumber`), `ClientID` INT unsigned , `fo_InquiryDate` DATE , `fo_DueDate` DATE , `fo_kelasifikasi` VARCHAR(100) not null default 'Unknown' , `fo_DeliveryDate` DATE , `fo_Logistic` INT(11) unsigned , `fo_Freight` FLOAT(10,2) default '0' , `fo_ShipName` INT unsigned , `fo_ShipAddress` INT unsigned , `fo_ShipCity` INT unsigned , `fo_ShipRegion` INT unsigned , `fo_ShipPostalCode` INT unsigned , `fo_ShipCountry` INT unsigned , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Inquiry', array('ClientID','fo_Logistic','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('DesignProposal', "create table if not exists `DesignProposal` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `InquiryID` INT unsigned , `fo_Type` VARCHAR(10) not null default 'Unknown' , `fo_Intro` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_RecSub` TINYBLOB not null , `fo_Submissiondate` DATE , `fo_contact_person` VARCHAR(100) , `fo_Price` DECIMAL(10,2) default '0.00' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('DesignProposal', array('InquiryID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ContractDeployment', "create table if not exists `ContractDeployment` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(250) not null , unique `DocconNumber_unique` (`DocconNumber`), `InquiryID` INT unsigned , `fo_Type` TEXT not null , `fo_Tajuk` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_ExeDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ContractDeployment', array('InquiryID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('employees', "create table if not exists `employees` (   `EmployeeID` INT not null auto_increment , primary key (`EmployeeID`), `EmpNo` VARCHAR(256) not null , unique `EmpNo_unique` (`EmpNo`), `Name` VARCHAR(100) , `BaseLocation` INT unsigned , `fo_TermEmployment` VARCHAR(50) , `fo_Photo` VARCHAR(40) , `fo_Position` VARCHAR(200) , `fo_BirthDate` DATE , `fo_HireDate` DATE , `fo_Address` VARCHAR(50) , `fo_City` VARCHAR(100) , `fo_Region` VARCHAR(100) , `fo_PostalCode` VARCHAR(10) , `fo_Country` VARCHAR(100) , `fo_HomePhone` VARCHAR(24) , `fo_Extension` VARCHAR(4) , `fo_Notes` TEXT , `fo_ReportsTo` INT , `fo_Acknowledgement` INT default '0' , `fo_Induction` TINYINT default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE employees ADD `field36` VARCHAR(40)","ALTER TABLE `employees` CHANGE `field36` `EmpNo` VARCHAR(256) ","ALTER TABLE `employees` ADD UNIQUE `EmpNo_unique` (`EmpNo`)"," ALTER TABLE `employees` CHANGE `EmpNo` `EmpNo` VARCHAR(256) not null "," ALTER TABLE `employees` CHANGE `FirstName` `FirstName` VARCHAR(100) ","ALTER TABLE `employees` DROP INDEX `FirstName`","ALTER TABLE `employees` DROP `LastName`","ALTER TABLE `employees` CHANGE `FirstName` `Name` VARCHAR(100) "));
		setupIndexes('employees', array('BaseLocation','fo_ReportsTo','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Recruitment', "create table if not exists `Recruitment` (   `RecruitID` INT not null auto_increment , primary key (`RecruitID`), `CompID` VARCHAR(200) not null , unique `CompID_unique` (`CompID`), `EmployeeID` INT , `ProjectTeamID` INT , `fo_RecruitmentSession` VARCHAR(40) , `fo_Description` TEXT , `fo_Date` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE `Recruitment` ADD `ProjectTeamID` INT not null auto_increment ","ALTER TABLE `Recruitment` DROP `ProjectTeamID`","ALTER TABLE `Recruitment` ADD `EmployeeID_1` INT ","ALTER TABLE `Recruitment` ADD INDEX `EmployeeID_1`","ALTER TABLE `Recruitment` CHANGE `EmployeeID_1` `ProjectTeamID` INT "));
		setupIndexes('Recruitment', array('EmployeeID','ProjectTeamID'));
		setupTable('PersonnalFile', "create table if not exists `PersonnalFile` (   `PersonalFileID` INT not null auto_increment , primary key (`PersonalFileID`), `FileID` VARCHAR(200) not null , unique `FileID_unique` (`FileID`), `EmployeeID` INT , `ProjectTeamID` INT , `fo_PersonalFileDesc` VARCHAR(40) , `fo_Description` TEXT , `fo_Date` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE `PersonnalFile` ADD `ProjectTeamID` INT ","ALTER TABLE `PersonnalFile` ADD INDEX `ProjectTeamID`"));
		setupIndexes('PersonnalFile', array('EmployeeID','ProjectTeamID'));
		setupTable('Competency', "create table if not exists `Competency` (   `CompetencyID` INT not null auto_increment , primary key (`CompetencyID`), `CompID` VARCHAR(200) not null , unique `CompID_unique` (`CompID`), `EmployeeID` INT , `ProjectTeamID` INT , `fo_CompetencySession` VARCHAR(40) , `fo_Description` TEXT , `fo_Date` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE `Competency` ADD `ProjectTeamID` INT ","ALTER TABLE `Competency` ADD INDEX `ProjectTeamID`"));
		setupIndexes('Competency', array('EmployeeID','ProjectTeamID'));
		setupTable('Training', "create table if not exists `Training` (   `TrainingID` INT not null auto_increment , primary key (`TrainingID`), `TraningNo` VARCHAR(100) not null , unique `TraningNo_unique` (`TraningNo`), `EmployeeID` INT , `ProjectTeamID` INT , `fo_TrainingSession` VARCHAR(40) , `fo_Classification` VARCHAR(40) , `fo_Description` TEXT , `fo_Date` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE `Training` ADD `ProjectTeamID` INT ","ALTER TABLE `Training` ADD INDEX `ProjectTeamID`"));
		setupIndexes('Training', array('EmployeeID','ProjectTeamID'));
		setupTable('JD_JS', "create table if not exists `JD_JS` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RecordNumber` VARCHAR(40) not null , unique `RecordNumber_unique` (`RecordNumber`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` VARCHAR(255) not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_EmployeeID` INT , `fo_ProjectTeamID` INT , `fo_JDDesc` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE `JD_JS` ADD `ProjectTeamID` INT ","ALTER TABLE `JD_JS` ADD INDEX `ProjectTeamID`","ALTER TABLE `JD_JS` CHANGE `ProjectTeamID` `fo_ProjectTeamID` INT "));
		setupIndexes('JD_JS', array('fo_EmployeeID','fo_ProjectTeamID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('InOutRegister', "create table if not exists `InOutRegister` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RecordNumber` VARCHAR(40) not null , unique `RecordNumber_unique` (`RecordNumber`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` VARCHAR(255) not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Delivdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('InOutRegister', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('vendor', "create table if not exists `vendor` (   `VendorID` INT(11) unsigned not null auto_increment , primary key (`VendorID`), `CompanyID` VARCHAR(200) not null , unique `CompanyID_unique` (`CompanyID`), `CopanyName` VARCHAR(100) , `fo_AVList` TINYINT default '0' , `fo_ContactTitle` VARCHAR(100) , `fo_Address` VARCHAR(100) , `fo_City` VARCHAR(50) , `fo_Region` VARCHAR(50) , `fo_PostalCode` VARCHAR(10) , `fo_Country` VARCHAR(50) , `fo_Phone` VARCHAR(24) , `fo_Fax` VARCHAR(24) , `fo_HomePage` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('vendor', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ManagingVendor', "create table if not exists `ManagingVendor` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ManagingVendNumber` VARCHAR(40) not null , unique `ManagingVendNumber_unique` (`ManagingVendNumber`), `DocItem` VARCHAR(255) not null , `fo_VendorID` INT(11) unsigned , `fo_DocumentDescription` VARCHAR(255) not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Auditdate` DATE , `fo_image` VARCHAR(40) , `fo_address` TEXT , `fo_city` VARCHAR(40) , `fo_state` VARCHAR(15) , `fo_zip` CHAR(8) , `fo_workphone` VARCHAR(40) , `fo_mobile` VARCHAR(40) , `fo_contactperson` VARCHAR(100) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ManagingVendor', array('fo_VendorID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('VenPerformance', "create table if not exists `VenPerformance` (   `id` INT unsigned not null auto_increment , primary key (`id`), `VendPerfNumber` VARCHAR(40) not null , unique `VendPerfNumber_unique` (`VendPerfNumber`), `DocItem` VARCHAR(255) not null , `fo_SupplierID` INT(11) unsigned , `fo_NewList` TINYINT default '0' , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(100) not null default 'Unknown' , `fo_Perfdate` DATE , `fo_image` VARCHAR(40) , `fo_address` TEXT , `fo_city` VARCHAR(40) , `fo_state` VARCHAR(15) , `fo_zip` CHAR(8) , `fo_workphone` VARCHAR(40) , `fo_mobile` VARCHAR(40) , `fo_contactperson` VARCHAR(100) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('VenPerformance', array('fo_SupplierID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Logistics', "create table if not exists `Logistics` (   `ShipperID` INT(11) unsigned not null auto_increment , primary key (`ShipperID`), `LogisticID` VARCHAR(200) not null , unique `LogisticID_unique` (`LogisticID`), `CompanyName` VARCHAR(200) not null , `fo_AVList` TINYINT default '0' , `fo_Phone` VARCHAR(24) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Logistics', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Inventory', "create table if not exists `Inventory` (   `id` INT unsigned not null auto_increment , primary key (`id`), `InventoryID` VARCHAR(100) not null , unique `InventoryID_unique` (`InventoryID`), `asstitle` VARCHAR(256) , `Description` TEXT , `fo_Type` VARCHAR(100) , `fo_Manufacturer` VARCHAR(250) , `fo_ModelNumber` VARCHAR(250) , `fo_SerialNumber` VARCHAR(250) , `fo_Condition` TEXT , `fo_history` VARCHAR(100) not null default 'Unknown' , `fo_Quantity` INT default '0' , `fo_UnitPrice` FLOAT(10,2) default '0' , `fo_Remarks` TEXT , `fo_date` DATE , `fo_ItemLocation` VARCHAR(100) , `fo_image` VARCHAR(40) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Inventory', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('CalibrationCtrl', "create table if not exists `CalibrationCtrl` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CalibrationID` VARCHAR(250) not null , unique `CalibrationID_unique` (`CalibrationID`), `Calibtitle` VARCHAR(256) , `fo_InventoryID` INT unsigned , `fo_CalCom` INT(11) unsigned , `fo_DurCal` TEXT , `fo_Delivdate` DATE , `fo_contact_person` VARCHAR(100) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('CalibrationCtrl', array('fo_InventoryID','fo_CalCom','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('WorkOrder', "create table if not exists `WorkOrder` (   `id` INT unsigned not null auto_increment , primary key (`id`), `WONumber` VARCHAR(40) not null , unique `WONumber_unique` (`WONumber`), `Task` VARCHAR(100) not null , `fo_Critical` VARCHAR(40) not null default 'Unknown' , `fo_EmployeeID` INT , `fo_Position` INT , `fo_BaseLocation` INT unsigned , `fo_JobInstruction` TEXT not null , `fo_DetailInstruction` TEXT , `fo_Resources` TEXT , `fo_Duedate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('WorkOrder', array('fo_EmployeeID','fo_BaseLocation','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWO', "create table if not exists `MWO` (   `id` INT unsigned not null auto_increment , primary key (`id`), `MWONumber` VARCHAR(200) not null , unique `MWONumber_unique` (`MWONumber`), `Critical` VARCHAR(40) not null default 'Unknown' , `fo_InventoryID` INT unsigned , `fo_Task` TEXT not null , `fo_Category` TEXT not null , `fo_JobInstruction` TEXT not null , `fo_DetailInstruction` TEXT , `fo_Resources` TEXT , `fo_Duedate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWO', array('fo_InventoryID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWOPlanned', "create table if not exists `MWOPlanned` (   `WMOPlannedID` INT unsigned not null auto_increment , primary key (`WMOPlannedID`), `PlannedID` INT unsigned not null , unique `PlannedID_unique` (`PlannedID`), `MwoID` INT unsigned default '0' , `fo_EmployeeID` INT , `fo_Position` INT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWOPlanned', array('MwoID','fo_EmployeeID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWOpreventive', "create table if not exists `MWOpreventive` (   `id` INT unsigned not null auto_increment , primary key (`id`), `PreventiveID` VARCHAR(200) not null , unique `PreventiveID_unique` (`PreventiveID`), `MwoID` INT unsigned default '0' , `fo_EmployeeID` INT , `fo_Position` INT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWOpreventive', array('MwoID','fo_EmployeeID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWOproactive', "create table if not exists `MWOproactive` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ProactiveID` VARCHAR(200) not null , unique `ProactiveID_unique` (`ProactiveID`), `MwoID` INT unsigned default '0' , `fo_EmployeeID` INT , `fo_Position` INT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWOproactive', array('MwoID','fo_EmployeeID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWConditionBased', "create table if not exists `MWConditionBased` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CondBaseID` VARCHAR(200) not null , unique `CondBaseID_unique` (`CondBaseID`), `MwoID` INT unsigned default '0' , `fo_EmployeeID` INT , `fo_Position` INT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWConditionBased', array('MwoID','fo_EmployeeID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWOReactive', "create table if not exists `MWOReactive` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ReactiveID` VARCHAR(200) not null , unique `ReactiveID_unique` (`ReactiveID`), `MwoID` INT unsigned default '0' , `fo_EmployeeID` INT , `fo_Position` INT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWOReactive', array('MwoID','fo_EmployeeID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MWOCorrective', "create table if not exists `MWOCorrective` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CorrectiveID` VARCHAR(200) not null , unique `CorrectiveID_unique` (`CorrectiveID`), `MwoID` INT unsigned default '0' , `fo_EmployeeID` INT , `fo_Position` INT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MWOCorrective', array('MwoID','fo_EmployeeID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('LogisticRequest', "create table if not exists `LogisticRequest` (   `id` INT unsigned not null auto_increment , primary key (`id`), `LogisticNumber` VARCHAR(100) not null , unique `LogisticNumber_unique` (`LogisticNumber`), `Market_Survey` VARCHAR(40) not null default 'Unknown' , `fo_ResourcesID` INT unsigned , `fo_ProjectID` INT unsigned , `fo_ShipVia` INT(11) unsigned , `fo_Deliverydate` DATE , `fo_address` TEXT , `fo_city` VARCHAR(40) , `fo_zip` CHAR(8) , `fo_Countrys` VARCHAR(100) , `fo_homephone` VARCHAR(40) , `fo_workphone` VARCHAR(40) , `fo_contactperson` VARCHAR(100) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('LogisticRequest', array('fo_ResourcesID','fo_ProjectID','fo_ShipVia','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('orders', "create table if not exists `orders` (   `id` INT unsigned not null auto_increment , primary key (`id`), `OrderID` VARCHAR(100) not null , unique `OrderID_unique` (`OrderID`), `Market_Survey` VARCHAR(40) not null default 'Unknown' , `fo_Classification` VARCHAR(40) not null default 'Unknown' , `fo_Critical` VARCHAR(40) not null default 'Unknown' , `fo_Justification` VARCHAR(40) not null default 'Unknown' , `fo_ProjectID` INT unsigned not null , `fo_InventoryID` INT unsigned not null , `fo_ItemID` INT not null , `fo_ProductID` INT default '0' , `fo_Description` VARCHAR(255) , `fo_Detail` TEXT , `fo_OrderDate` DATE , `fo_RequiredDate` DATE , `fo_ShippedDate` DATE , `fo_ShipVia` INT(11) unsigned , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('orders', array('fo_ProjectID','fo_InventoryID','fo_ItemID','fo_ShipVia','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Quotation', "create table if not exists `Quotation` (   `id` INT unsigned not null auto_increment , primary key (`id`), `QuoID` VARCHAR(100) not null , unique `QuoID_unique` (`QuoID`), `OrderID` INT unsigned default '0' , `fo_Vendor` INT(11) unsigned default '0' , `fo_ShipVia` INT(11) unsigned , `fo_Price` DECIMAL(10,2) default '0.00' , `fo_Description` TEXT , `fo_Discount` FLOAT(10,2) default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Quotation', array('OrderID','fo_Vendor','fo_ShipVia','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('PurchaseOrder', "create table if not exists `PurchaseOrder` (   `id` INT unsigned not null auto_increment , primary key (`id`), `POID` VARCHAR(100) not null , unique `POID_unique` (`POID`), `OrderID` INT unsigned default '0' , `fo_Vendor` INT(11) unsigned default '0' , `fo_ShipVia` INT(11) unsigned , `fo_Price` DECIMAL(10,2) default '0.00' , `fo_Description` TEXT , `fo_Discount` FLOAT(10,2) default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PurchaseOrder', array('OrderID','fo_Vendor','fo_ShipVia','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('DeliveryOrder', "create table if not exists `DeliveryOrder` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DOID` VARCHAR(100) not null , unique `DOID_unique` (`DOID`), `OrderID` INT unsigned default '0' , `fo_Vendor` INT(11) unsigned default '0' , `fo_ShipVia` INT(11) unsigned , `fo_Description` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('DeliveryOrder', array('OrderID','fo_Vendor','fo_ShipVia','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('AccountPayables', "create table if not exists `AccountPayables` (   `id` INT unsigned not null auto_increment , primary key (`id`), `APID` VARCHAR(100) not null , unique `APID_unique` (`APID`), `OrderID` INT unsigned default '0' , `fo_Vendor` INT(11) unsigned default '0' , `fo_ShipVia` INT(11) unsigned , `fo_UnitPrice` FLOAT(10,2) default '0' , `fo_Description` TEXT , `fo_Discount` FLOAT(10,2) default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('AccountPayables', array('OrderID','fo_Vendor','fo_ShipVia','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Item', "create table if not exists `Item` (   `ProductID` INT not null auto_increment , primary key (`ProductID`), `ItemID` VARCHAR(200) not null , unique `ItemID_unique` (`ItemID`), `ProductName` VARCHAR(50) , `fo_SupplierID` INT(11) unsigned , `fo_CategoryID` INT , `fo_QuantityPerUnit` VARCHAR(50) , `fo_UnitPrice` FLOAT(10,2) default '0' , `fo_UnitsInStock` SMALLINT default '0' , `fo_UnitsOnOrder` SMALLINT(6) default '0' , `fo_ReorderLevel` SMALLINT default '0' , `fo_Description` TEXT , `fo_Discontinued` TINYINT default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Item', array('fo_SupplierID','fo_CategoryID'));
		setupTable('categories', "create table if not exists `categories` (   `CategoryID` INT not null auto_increment , primary key (`CategoryID`), `CategoryName` VARCHAR(50) not null , unique `CategoryName_unique` (`CategoryName`), `fo_Description` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Picture` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupTable('batches', "create table if not exists `batches` (   `id` INT unsigned not null auto_increment , primary key (`id`), `batch_no` VARCHAR(40) not null , unique `batch_no_unique` (`batch_no`), `fo_item` INT , `fo_suppliers` INT(11) unsigned , `fo_manudate` DATE , `fo_expdate` DATE , `fo_Quantity` DECIMAL(10,0) , `ot_FileLoc` VARCHAR(100) , `fo_otherdetails` TEXT , `fo_comments` TEXT , `fo_SharedLink1` VARCHAR(200) , `fo_SharedLink2` VARCHAR(200) , `fo_Ref01` VARCHAR(40) , `fo_Ref02` VARCHAR(40) , `fo_Photo` VARCHAR(40) , `fo_ap_filed` DATETIME , `fo_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('batches', array('fo_item','fo_suppliers'));
		setupTable('transactions', "create table if not exists `transactions` (   `id` INT unsigned not null auto_increment , primary key (`id`), `TransCode` VARCHAR(256) not null , unique `TransCode_unique` (`TransCode`), `fo_transaction_date` DATE , `fo_item` INT , `fo_ResourcesID` INT unsigned , `fo_transactiontype` VARCHAR(40) not null , `fo_quantity` DECIMAL(10,2) default '1.00' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('transactions', array('fo_item','fo_ResourcesID'));
		setupTable('CommConsParticipate', "create table if not exists `CommConsParticipate` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ccpID` VARCHAR(40) not null , unique `ccpID_unique` (`ccpID`), `WorkLocationID` INT unsigned , `fo_WorkDate` DATE , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('CommConsParticipate', array('WorkLocationID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ToolBoxMeeting', "create table if not exists `ToolBoxMeeting` (   `id` INT unsigned not null auto_increment , primary key (`id`), `tbmID` VARCHAR(100) not null , unique `tbmID_unique` (`tbmID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ToolBoxMeeting', array('ccpID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Bi_WeeklyMeeting', "create table if not exists `Bi_WeeklyMeeting` (   `id` INT unsigned not null auto_increment , primary key (`id`), `BwmID` VARCHAR(100) not null , unique `BwmID_unique` (`BwmID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Bi_WeeklyMeeting', array('ccpID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('QuarterlyMeeting', "create table if not exists `QuarterlyMeeting` (   `id` INT unsigned not null auto_increment , primary key (`id`), `QmID` VARCHAR(100) not null , unique `QmID_unique` (`QmID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('QuarterlyMeeting', array('ccpID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Campaign', "create table if not exists `Campaign` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CampaignID` VARCHAR(100) not null , unique `CampaignID_unique` (`CampaignID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Campaign', array('ccpID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('DrillNInspection', "create table if not exists `DrillNInspection` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DillID` VARCHAR(100) not null , unique `DillID_unique` (`DillID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('DrillNInspection', array('ccpID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ManagementVisit', "create table if not exists `ManagementVisit` (   `id` INT unsigned not null auto_increment , primary key (`id`), `MgtVstID` VARCHAR(100) not null , unique `MgtVstID_unique` (`MgtVstID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ManagementVisit', array('ccpID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('EventNotification', "create table if not exists `EventNotification` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ENID` VARCHAR(100) not null , unique `ENID_unique` (`ENID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('EventNotification', array('ccpID'));
		setupTable('ActCard', "create table if not exists `ActCard` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ACID` VARCHAR(100) not null , unique `ACID_unique` (`ACID`), `ccpID` INT unsigned default '0' , `fo_Desc` TEXT , `fo_RequiredDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ActCard', array('ccpID'));
		setupTable('KM', "create table if not exists `KM` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocumentName` VARCHAR(250) not null , unique `DocumentName_unique` (`DocumentName`), `fo_Description` TEXT , `fo_Reference` VARCHAR(40) not null , `fo_Volume` VARCHAR(100) not null , `fo_Classification` VARCHAR(100) not null default 'Unknown' , `fo_Class` VARCHAR(100) default 'Unknown' , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('KM', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('LegalRegister', "create table if not exists `LegalRegister` (   `id` INT unsigned not null auto_increment , primary key (`id`), `LRNumber` VARCHAR(40) not null , unique `LRNumber_unique` (`LRNumber`), `LegalItem` VARCHAR(255) not null , `fo_LRDescription` TEXT , `fo_Classification` VARCHAR(100) not null default 'Unknown' , `fo_Class` VARCHAR(100) not null default 'Unknown' , `fo_date` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('LegalRegister', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('RiskandOpportunity', "create table if not exists `RiskandOpportunity` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RISKid` VARCHAR(250) not null , unique `RISKid_unique` (`RISKid`), `Item` VARCHAR(250) not null , `fo_Description` TEXT , `fo_Class` VARCHAR(100) not null default 'Unknown' , `fo_Riskregister` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('RiskandOpportunity', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('DocControl', "create table if not exists `DocControl` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(250) not null , unique `DocconNumber_unique` (`DocconNumber`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Class` VARCHAR(100) not null default 'Unknown' , `fo_DocumentType` TEXT not null , `fo_Rev` VARCHAR(256) default '00' , `fo_date` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('DocControl', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('DCN', "create table if not exists `DCN` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(255) not null , unique `DocconNumber_unique` (`DocconNumber`), `DCCID` INT unsigned default '0' , `fo_DCCITEM` INT unsigned default '0' , `fo_Description` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('DCN', array('DCCID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ObsoleteRec', "create table if not exists `ObsoleteRec` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(255) not null , unique `DocconNumber_unique` (`DocconNumber`), `DCCID` INT unsigned default '0' , `fo_DCCITEM` INT unsigned default '0' , `fo_Description` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ObsoleteRec', array('DCCID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('QA', "create table if not exists `QA` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `BaseLocation` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Class` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('QA', array('BaseLocation','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ERP', "create table if not exists `ERP` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `BaseLocation` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Registerdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ERP', array('BaseLocation','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('WorkEnvMonitoring', "create table if not exists `WorkEnvMonitoring` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `BaseLocation` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherDetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('WorkEnvMonitoring', array('BaseLocation','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ScheduleWaste', "create table if not exists `ScheduleWaste` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `worklocID` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ScheduleWaste', array('worklocID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('IncidentReporting', "create table if not exists `IncidentReporting` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `BaseLocation` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('IncidentReporting', array('BaseLocation','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MgtofChange', "create table if not exists `MgtofChange` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `title` VARCHAR(250) , `fo_Desc` TEXT , `fo_class` TEXT not null , `fo_regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MgtofChange', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('IMStrackingNmonitoring', "create table if not exists `IMStrackingNmonitoring` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `WorklocID` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('IMStrackingNmonitoring', array('WorklocID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('IMSDataAnalysis', "create table if not exists `IMSDataAnalysis` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `worklocID` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('IMSDataAnalysis', array('worklocID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Audit', "create table if not exists `Audit` (   `id` INT unsigned not null auto_increment , primary key (`id`), `AuditNo` VARCHAR(40) not null , unique `AuditNo_unique` (`AuditNo`), `Rectitle` VARCHAR(256) , `fo_Desc` TEXT , `fo_Auditor` VARCHAR(10) not null , `fo_Classification` TEXT not null , `fo_Regdate` DATE , `fo_AuditMemo` TINYINT default '0' , `fo_AuditPlan` TINYINT default '0' , `fo_AuditNote` TINYINT default '0' , `fo_AuditReport` TINYINT default '0' , `fo_NoObservation` SMALLINT default '0' , `fo_NoMinorNC` SMALLINT default '0' , `fo_NoMajorNC` SMALLINT default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Audit', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('NonConformance', "create table if not exists `NonConformance` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `worklocID` INT unsigned , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Regdate` DATE , `fo_ClosedIssue` TINYINT default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('NonConformance', array('worklocID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ContinualImprovement', "create table if not exists `ContinualImprovement` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CAPARno` VARCHAR(40) not null , unique `CAPARno_unique` (`CAPARno`), `RecTitle` VARCHAR(256) , `fo_Class` VARCHAR(100) not null , `fo_CAPAR` TEXT not null , `fo_Desc` TEXT , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ContinualImprovement', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('StakeholderSatisfaction', "create table if not exists `StakeholderSatisfaction` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RecordID` VARCHAR(256) not null , unique `RecordID_unique` (`RecordID`), `RecTitle` VARCHAR(256) , `fo_ProjectId` INT unsigned not null , `fo_Recources` INT unsigned not null , `fo_ClientID` INT unsigned not null , `fo_gender` VARCHAR(10) not null , `fo_SurveyType` TEXT not null , `fo_Stakeholder` VARCHAR(256) , `fo_Description` TEXT , `fo_Regdate` DATE , `fo_website` VARCHAR(200) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('StakeholderSatisfaction', array('fo_ProjectId','fo_Recources','fo_ClientID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MRM', "create table if not exists `MRM` (   `id` INT unsigned not null auto_increment , primary key (`id`), `DocconNumber` VARCHAR(40) not null , unique `DocconNumber_unique` (`DocconNumber`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Classification` VARCHAR(10) not null default 'Unknown' , `fo_Impact` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MRM', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('projects', "create table if not exists `projects` (   `Id` INT unsigned not null auto_increment , primary key (`Id`), `projectID` VARCHAR(200) not null , unique `projectID_unique` (`projectID`), `Name` VARCHAR(250) , `fo_ProjectIndication` TEXT not null , `fo_DocumentDescription` TEXT not null , `fo_StartDate` DATE , `fo_EndDate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('projects', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('WorkLocation', "create table if not exists `WorkLocation` (   `id` INT unsigned not null auto_increment , primary key (`id`), `BaseLocation` VARCHAR(250) not null , unique `BaseLocation_unique` (`BaseLocation`), `DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Type` VARCHAR(40) not null default 'Unknown' , `fo_Sector` VARCHAR(256) , `fo_Zone` VARCHAR(256) , `fo_Country` VARCHAR(15) , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('WorkLocation', array('ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('WorkPermit', "create table if not exists `WorkPermit` (   `id` INT unsigned not null auto_increment , primary key (`id`), `RecNum` VARCHAR(100) not null , unique `RecNum_unique` (`RecNum`), `WrLocID` INT unsigned default '0' , `fo_Type` VARCHAR(250) not null default 'Unknown' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('WorkPermit', array('WrLocID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ProjectTeam', "create table if not exists `ProjectTeam` (   `ProjectTeamID` INT not null auto_increment , primary key (`ProjectTeamID`), `EmpNo` VARCHAR(256) not null , unique `EmpNo_unique` (`EmpNo`), `Name` VARCHAR(100) , `BaseLocation` INT unsigned , `fo_TermEmployment` VARCHAR(50) , `fo_Photo` VARCHAR(40) , `fo_Position` VARCHAR(200) , `fo_BirthDate` DATE , `fo_HireDate` DATE , `fo_Address` VARCHAR(50) , `fo_City` VARCHAR(100) , `fo_Region` VARCHAR(100) , `fo_PostalCode` VARCHAR(10) , `fo_Country` VARCHAR(100) , `fo_HomePhone` VARCHAR(24) , `fo_Extension` VARCHAR(4) , `fo_Notes` TEXT , `fo_ReportsTo` INT , `fo_Acknowledgement` INT default '0' , `fo_Induction` TINYINT default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent, array( "ALTER TABLE `employees_1` RENAME `ProjectTeam`","UPDATE `membership_userrecords` SET `tableName`='ProjectTeam' where `tableName`='employees_1'","UPDATE `membership_userpermissions` SET `tableName`='ProjectTeam' where `tableName`='employees_1'","UPDATE `membership_grouppermissions` SET `tableName`='ProjectTeam' where `tableName`='employees_1'","ALTER TABLE `ProjectTeam` CHANGE `EmployeeID` `ProjectTeamID` INT not null auto_increment ","ALTER TABLE `ProjectTeam` ADD `EmpNo` VARCHAR(256) not null ","ALTER TABLE `ProjectTeam` ADD UNIQUE `EmpNo_unique` (`EmpNo`)","ALTER TABLE `ProjectTeam` DROP INDEX `FirstName`"," ALTER TABLE `ProjectTeam` CHANGE `FirstName` `FirstName` VARCHAR(100) ","ALTER TABLE `ProjectTeam` DROP `LastName`","ALTER TABLE `ProjectTeam` CHANGE `FirstName` `Name` VARCHAR(100) "));
		setupIndexes('ProjectTeam', array('BaseLocation','fo_ReportsTo','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('resources', "create table if not exists `resources` (   `Id` INT unsigned not null auto_increment , primary key (`Id`), `ResourcesID` VARCHAR(200) not null , unique `ResourcesID_unique` (`ResourcesID`), `Name` VARCHAR(250) , `fo_Type` TEXT not null , `fo_Description` TEXT , `fo_Available` VARCHAR(40) default '1' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupTable('PROInitiation', "create table if not exists `PROInitiation` (   `id` INT unsigned not null auto_increment , primary key (`id`), `InitiationNo` VARCHAR(200) not null , unique `InitiationNo_unique` (`InitiationNo`), `ProjectsID` INT unsigned , `fo_InitiationForm` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PROInitiation', array('ProjectsID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('PROPlanning', "create table if not exists `PROPlanning` (   `id` INT unsigned not null auto_increment , primary key (`id`), `PlanningNo` VARCHAR(200) not null , unique `PlanningNo_unique` (`PlanningNo`), `ProjectsID` INT unsigned , `fo_RelatedDocument` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PROPlanning', array('ProjectsID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('PROExecution', "create table if not exists `PROExecution` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ExecutionNo` VARCHAR(200) not null , unique `ExecutionNo_unique` (`ExecutionNo`), `ProjectsID` INT unsigned , `fo_Classification` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PROExecution', array('ProjectsID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('DailyProgressReport', "create table if not exists `DailyProgressReport` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ProgressReportId` VARCHAR(100) not null , unique `ProgressReportId_unique` (`ProgressReportId`), `DPRID` INT unsigned default '0' , `fo_Class` VARCHAR(40) not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('DailyProgressReport', array('DPRID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('MonthlyTimesheet', "create table if not exists `MonthlyTimesheet` (   `id` INT unsigned not null auto_increment , primary key (`id`), `TimesheetID` VARCHAR(100) not null , unique `TimesheetID_unique` (`TimesheetID`), `MTSID` INT unsigned default '0' , `fo_Class` VARCHAR(40) not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('MonthlyTimesheet', array('MTSID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Breakdown', "create table if not exists `Breakdown` (   `Id` INT unsigned not null auto_increment , primary key (`Id`), `recID` VARCHAR(256) not null , unique `recID_unique` (`recID`), `MTSID` INT unsigned , `ResourceId` INT unsigned , `Title` VARCHAR(256) not null , `fo_Description` TEXT , `ot_FileLoc` VARCHAR(100) , `ot_otherDetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Breakdown', array('MTSID','ResourceId','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('PROControlMonitoring', "create table if not exists `PROControlMonitoring` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ContMonitNo` VARCHAR(200) not null , unique `ContMonitNo_unique` (`ContMonitNo`), `ProjectsID` INT unsigned , `fo_AuditInspection` TEXT not null , `fo_Classification` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PROControlMonitoring', array('ProjectsID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('PROVariation', "create table if not exists `PROVariation` (   `id` INT unsigned not null auto_increment , primary key (`id`), `VariationNo` VARCHAR(200) not null , unique `VariationNo_unique` (`VariationNo`), `ProjectsID` INT unsigned , `fo_Classification` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PROVariation', array('ProjectsID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('PROCompletion', "create table if not exists `PROCompletion` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CompletionNo` VARCHAR(200) not null , unique `CompletionNo_unique` (`CompletionNo`), `ProjectsID` INT unsigned , `fo_Classification` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_Regdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('PROCompletion', array('ProjectsID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('Receivables', "create table if not exists `Receivables` (   `id` INT unsigned not null auto_increment , primary key (`id`), `ClaimNo` VARCHAR(200) not null , unique `ClaimNo_unique` (`ClaimNo`), `ProjectsID` INT unsigned , `ResourcesID` INT unsigned , `fo_Classification` TEXT not null , `fo_DocItem` VARCHAR(255) not null , `fo_UnitPrice` FLOAT(10,2) default '0' , `fo_DocumentDescription` TEXT not null , `fo_Registerdate` DATE , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('Receivables', array('ProjectsID','ResourcesID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('ClaimRecord', "create table if not exists `ClaimRecord` (   `id` INT unsigned not null auto_increment , primary key (`id`), `CRID` VARCHAR(100) not null , unique `CRID_unique` (`CRID`), `ReceivablesID` INT unsigned default '0' , `fo_DocItem` VARCHAR(255) not null , `fo_DocumentDescription` TEXT not null , `fo_UnitPrice` FLOAT(10,2) default '0' , `ot_FileLoc` VARCHAR(100) , `ot_otherdetails` TEXT , `ot_comments` TEXT , `ot_SharedLink1` VARCHAR(200) , `ot_SharedLink2` VARCHAR(200) , `ot_Ref01` VARCHAR(40) , `ot_Ref02` VARCHAR(40) , `ot_Photo` VARCHAR(40) , `ot_ap_Review` INT unsigned , `ot_ap_RevComment` TEXT , `ot_ap_Approval` INT unsigned , `ot_ap_ApprComment` TEXT , `ot_ap_QC` INT unsigned , `ot_ap_QCComment` TEXT , `ot_ap_filed` DATETIME , `ot_ap_lastmodified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ClaimRecord', array('ReceivablesID','ot_ap_Review','ot_ap_Approval','ot_ap_QC'));
		setupTable('TeamSoftBoard', "create table if not exists `TeamSoftBoard` (   `Postid` INT unsigned not null auto_increment , primary key (`Postid`), `Title` VARCHAR(250) not null , unique `Title_unique` (`Title`), `image` VARCHAR(40) , `TextPost` TEXT , `website` VARCHAR(200) , `Ref01` VARCHAR(40) , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);
		setupTable('SoftboardComment', "create table if not exists `SoftboardComment` (   `RunningID` INT unsigned not null auto_increment , primary key (`RunningID`), `PostID` INT unsigned default '0' , `TextPost` TEXT , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('SoftboardComment', array('PostID'));
		setupTable('IMSReport', "create table if not exists `IMSReport` (   `Postid` INT unsigned not null auto_increment , primary key (`Postid`), `Title` VARCHAR(40) not null , unique `Title_unique` (`Title`), `image` VARCHAR(40) , `TextPost` TEXT , `website` VARCHAR(200) , `Ref01` VARCHAR(40) , `ClosedIssue` TINYINT default '0' , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);
		setupTable('ReportComment', "create table if not exists `ReportComment` (   `RunningID` INT unsigned not null auto_increment , primary key (`RunningID`), `PostID` INT unsigned default '0' , `TextPost` TEXT , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);
		setupIndexes('ReportComment', array('PostID'));
		setupTable('Leadership', "create table if not exists `Leadership` (   `id` INT unsigned not null auto_increment , primary key (`id`), `Status` VARCHAR(40) not null , `Description` TEXT , `other_details` TEXT , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);
		setupTable('Approval', "create table if not exists `Approval` (   `id` INT unsigned not null auto_increment , primary key (`id`), `Status` VARCHAR(40) not null , `Description` TEXT , `other_details` TEXT , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);
		setupTable('IMSControl', "create table if not exists `IMSControl` (   `id` INT unsigned not null auto_increment , primary key (`id`), `Status` VARCHAR(40) not null , `Description` TEXT , `other_details` TEXT , `filed` DATETIME , `last_modified` DATETIME ) CHARSET latin1", $silent);


		// save MD5
		if($fp=@fopen(dirname(__FILE__).'/setup.md5', 'w')){
			fwrite($fp, $thisMD5);
			fclose($fp);
		}
	}


	function setupIndexes($tableName, $arrFields){
		if(!is_array($arrFields)){
			return false;
		}

		foreach($arrFields as $fieldName){
			if(!$res=@db_query("SHOW COLUMNS FROM `$tableName` like '$fieldName'")){
				continue;
			}
			if(!$row=@db_fetch_assoc($res)){
				continue;
			}
			if($row['Key']==''){
				@db_query("ALTER TABLE `$tableName` ADD INDEX `$fieldName` (`$fieldName`)");
			}
		}
	}


	function setupTable($tableName, $createSQL='', $silent=true, $arrAlter=''){
		global $Translation;
		ob_start();

		echo '<div style="padding: 5px; border-bottom:solid 1px silver; font-family: verdana, arial; font-size: 10px;">';

		// is there a table rename query?
		if(is_array($arrAlter)){
			$matches=array();
			if(preg_match("/ALTER TABLE `(.*)` RENAME `$tableName`/", $arrAlter[0], $matches)){
				$oldTableName=$matches[1];
			}
		}

		if($res=@db_query("select count(1) from `$tableName`")){ // table already exists
			if($row = @db_fetch_array($res)){
				echo str_replace("<TableName>", $tableName, str_replace("<NumRecords>", $row[0],$Translation["table exists"]));
				if(is_array($arrAlter)){
					echo '<br>';
					foreach($arrAlter as $alter){
						if($alter!=''){
							echo "$alter ... ";
							if(!@db_query($alter)){
								echo '<span class="label label-danger">' . $Translation['failed'] . '</span>';
								echo '<div class="text-danger">' . $Translation['mysql said'] . ' ' . db_error(db_link()) . '</div>';
							}else{
								echo '<span class="label label-success">' . $Translation['ok'] . '</span>';
							}
						}
					}
				}else{
					echo $Translation["table uptodate"];
				}
			}else{
				echo str_replace("<TableName>", $tableName, $Translation["couldnt count"]);
			}
		}else{ // given tableName doesn't exist

			if($oldTableName!=''){ // if we have a table rename query
				if($ro=@db_query("select count(1) from `$oldTableName`")){ // if old table exists, rename it.
					$renameQuery=array_shift($arrAlter); // get and remove rename query

					echo "$renameQuery ... ";
					if(!@db_query($renameQuery)){
						echo '<span class="label label-danger">' . $Translation['failed'] . '</span>';
						echo '<div class="text-danger">' . $Translation['mysql said'] . ' ' . db_error(db_link()) . '</div>';
					}else{
						echo '<span class="label label-success">' . $Translation['ok'] . '</span>';
					}

					if(is_array($arrAlter)) setupTable($tableName, $createSQL, false, $arrAlter); // execute Alter queries on renamed table ...
				}else{ // if old tableName doesn't exist (nor the new one since we're here), then just create the table.
					setupTable($tableName, $createSQL, false); // no Alter queries passed ...
				}
			}else{ // tableName doesn't exist and no rename, so just create the table
				echo str_replace("<TableName>", $tableName, $Translation["creating table"]);
				if(!@db_query($createSQL)){
					echo '<span class="label label-danger">' . $Translation['failed'] . '</span>';
					echo '<div class="text-danger">' . $Translation['mysql said'] . db_error(db_link()) . '</div>';
				}else{
					echo '<span class="label label-success">' . $Translation['ok'] . '</span>';
				}
			}
		}

		echo "</div>";

		$out=ob_get_contents();
		ob_end_clean();
		if(!$silent){
			echo $out;
		}
	}
?>